### PR TITLE
Corrected ReadMe file to refer to correct parameters for public API

### PR DESCRIPTION
**Pull request by rjperrella**
This is a documentation change only.

### CODE REVIEW

**Comment by jared-stilwell** [comment]
@rjperrella Thanks for the PR. I landed an update to the travis config; while I suspect there is a deeper issue with the unit tests, rebasing your branch off the latest master branch will remove v0.10 from the travis run and most likely come back successful.

**Comment by rjperrella** [comment]
Hi Jared,
I'm a complete newbie when it comes to git so I understand only a bit of what you've said.  Should I reapply my changes (which are incredibly minor) to the current master?
 -Ron 

    On Tuesday, March 15, 2016 1:02 AM, Jared Stilwell <notifications@github.com> wrote:
 

 @rjperrella Thanks for the PR. I landed an update to the travis config; while I suspect there is a deeper issue with the unit tests, rebasing your branch off the latest master branch will remove v0.10 from the travis run and most likely come back successful.—

**Comment by rjperrella** [comment]
Ok - so, if I understand (I'm a git newbie), it would be best for me to withdraw the PR and apply my changes to the new master branch?

**Comment by jared-stilwell** [comment]
@rjperrella no worries. You might read through [this](http://gitready.com/intermediate/2009/02/12/easily-fetching-upstream-changes.html) to see how to add an "upstream" remote, if you haven't already done this. Once you're confident you have the latest changes in your fork of this project, then you should only need to checkout your branch and [`git rebase master`](http://gitready.com/intermediate/2009/01/31/intro-to-rebase.html).

This will reconstruct your commit on top of the latest changes I landed in master recently, and will consequently run the Travis CI checks with the latest changes as well.

**Pull request closed without merging**
